### ISSUE TITLE
[Bug]Failed repeatedly to fetch user information.

### ISSUE THREAD

**Issue by RicardoLBW** [Kazawaryu/Nike-Run-Errands-Wechat-Mini-Program#1]
I'm trying to use the mini program, but failed repeatedly to fetch user information. I'm sure that this is my first time using it and did not config anything? How it append? @Kazawaryu

**Comment by Kazawaryu** [comment]
I'm glad to hear you've successfully deployed our project! The likely reason for the issues you encountered is that you may have forgotten to set the **AppID** in your WeChat Mini Program IDE. Additionally, make sure you've also set the token in the code files.

I hope this could help you.
